---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newflask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newflask
  template:
    metadata:
      labels:
        app: newflask
    spec:
      containers:
      - name: newflask
        image: anieelorez/newflask:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: newflask-service
spec:
  selector:
    app: newflask
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
