name: Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build and push Docker image
      run: |
        docker build -t imagename .
        docker tag imagename anieelorez/newflask:latest
        docker login -u ${{ secrets.Dockerhub_username }} -p ${{ secrets.Dockerhub_token }}
        docker push anieelorez/newflask:latest
      env:
        DOCKER_CLI_ACI: 1

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Docker pull image
      run: docker pull anieelorez/newflask:latest
    - name: Image scan
      run: trivy image anieelorez/newflask:latest > trivyimagedeploy.txt
    - name: Deploy to container
      run: docker run -d --name swiggy-clone1 -p 3000:3000 aakibkhan1212/swiggy-clone:latest
    - name: Update kubeconfig
      run: azure aks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment-service.yml
