#This GitHub documentation outlines the Build workflow, which is responsible for building and deploying a Docker image for the project.
#The Build workflow is triggered on pushes to the main branch. It consists of two jobs: build and deploy.
#Triggered when changes are pushed to the main branch.
name: Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      #Checks out the code from the repository using the actions/checkout action.
    - uses: actions/checkout@v3
      #Builds a Docker image tagged with imagename.
    - name: Build and push Docker image
      run: |
        docker build -t imagename .
        docker tag imagename anieelorez/newflask:latest
        docker login -u ${{ secrets.Dockerhub_username }} -p ${{ secrets.Dockerhub_token }}
        docker push anieelorez/newflask:latest
      env:
        DOCKER_CLI_ACI: 1

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    # Pulls the Docker image anieelorez/newflask:latest from Docker Hub.
    - name: Docker pull image
      run: docker pull anieelorez/newflask:latest
    # Scans the Docker image using Trivy and saves the scan results to trivyimagedeploy.txt.
    - name: Image scan
      run: trivy image anieelorez/newflask:latest > trivyimagedeploy.txt
    # Runs a Docker container named newflask from the pulled Docker image, mapping port 3000 on the host to port 3000 on the container.
    - name: Deploy to container
      run: docker run -d --name newflask -p 3000:3000 anieelorez/newflask:latest
    #  Updates the Kubernetes configuration (kubeconfig) for the Azure Kubernetes Service (AKS) cluster named EKS_CLOUD in the ap-south-1 region.
    - name: Update kubeconfig
      run: azure aks --region ap-south-1 update-kubeconfig --name EKS_CLOUD
    # Applies the Kubernetes deployment and service configurations defined in deployment-service.yml.
    - name: Deploy to Kubernetes
      run: kubectl apply -f deployment-service.yml
